version : '3.8'
services:
  web:
    container_name: devops
    image: ${IMAGE}
    command: gunicorn devops.wsgi:application --bind 0.0.0.0:8000
    env_file :
        - .env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
  nginx-proxy:
    container_name : nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    env_file :
      - .env.nginx-proxy
    depends_on:
      - nginx-proxy
  db:
    image: postgres:15-alpine
    container_name : db
    environment:
      - POSTGRES_USER=wordcountly123
      - POSTGRES_PASSWORD=wordcountly@123
      - POSTGRES_DB=wordcountly
    volumes :
      - wordcountly:/var/lib/postgresql/data
volumes:
  postgres_data:
  wordcountly:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:

